"""empty message

Revision ID: 3792c1534273
Revises: 
Create Date: 2018-11-14 21:06:46.251303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3792c1534273'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    op.drop_table('post')
    op.drop_table('post_tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.Column('tag_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], [u'post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], [u'tag.id'], )
    )
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=140), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=140), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tag',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
